-- Create keycloak schema if it doesn't exist
CREATE SCHEMA IF NOT EXISTS keycloak;

-- Grant permissions to the dev user
GRANT ALL PRIVILEGES ON SCHEMA keycloak TO dev;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA keycloak TO dev;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA keycloak TO dev;
ALTER DEFAULT PRIVILEGES IN SCHEMA keycloak GRANT ALL ON TABLES TO dev;
ALTER DEFAULT PRIVILEGES IN SCHEMA keycloak GRANT ALL ON SEQUENCES TO dev;