CREATE SCHEMA IF NOT EXISTS keycloak;
GRANT ALL PRIVILEGES ON SCHEMA keycloak TO prod;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA keycloak TO prod;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA keycloak TO prod;
ALTER DEFAULT PRIVILEGES IN SCHEMA keycloak GRANT ALL ON TABLES TO prod;
ALTER DEFAULT PRIVILEGES IN SCHEMA keycloak GRANT ALL ON SEQUENCES TO prod;
