name: Test CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Test api
        working-directory: ./proyecto-final/api
        run: mvn test jacoco:report

      - name: Upload coverage report
        working-directory: ./proyecto-final/api
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-report
          path: target/site/jacoco